version: '3.8'

networks:
  compose_bounsel_engine:
    external: true

services:
  saturdays-pdf-recognition:
    build:
      context: ${CI_PROJECT_DIR}
      dockerfile: ${CI_PROJECT_DIR}/devops/dockerfiles/Dockerfile
      cache_from:
        - pdf-recognition
    container_name: pdf-recognition
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '20m'
    ports:
      - 5020:5020
    environment:
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      API_KEY: ${API_KEY}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5020']
      interval: 60s
      timeout: 5s
      retries: 30
    networks:
      - compose_bounsel_engine
