deploy_staging:
  stage: deploy 
  image: docker/compose:latest
  services:
    - name: docker:dind
  environment:
    name: staging
  tags:
    - build
  variables:
    DOCKER_COMPOSE_PATH: '${CI_PROJECT_DIR}/devops/compose/docker-compose.staging.yml'
    ENV_FILE: '${CI_PROJECT_DIR}/.env'
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
    DOCKER_DRIVER: overlay2
    SSH_SERVER: 'ssh://${SSH_AUTH_USER}@${SSH_AUTH_HOST}'
  before_script:
    - 'which ssh-agent || ( apk --update add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
    - echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cp $APP_ENV_FILE $ENV_FILE
  script:
    - docker-compose --env-file $ENV_FILE -f $DOCKER_COMPOSE_PATH --host $SSH_SERVER pull
    - docker-compose --env-file $ENV_FILE -f $DOCKER_COMPOSE_PATH --host $SSH_SERVER build
    - docker-compose --env-file $ENV_FILE -f $DOCKER_COMPOSE_PATH --host $SSH_SERVER up -d
  only:
    refs:
      - staging
    changes:
      - devops/src/**/*
      - devops/compose/**/*
      - devops/pipelines/**/*
      - devops/dockerfiles/**/*

destroy_staging:
  stage: cleanup 
  image: docker/compose:latest
  services:
    - name: docker:dind
  environment:
    name: staging
  variables:
    DOCKER_COMPOSE_PATH: '${CI_PROJECT_DIR}/devops/compose/docker-compose.staging.yml'
    ENV_FILE: '${CI_PROJECT_DIR}/.env'
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
    DOCKER_DRIVER: overlay2
    SSH_SERVER: 'ssh://${SSH_AUTH_USER}@${SSH_AUTH_HOST}'
  before_script:
    - 'which ssh-agent || ( apk --update add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
    - echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cp $APP_ENV_FILE $ENV_FILE
  script:
    - docker-compose --env-file $ENV_FILE -f $DOCKER_COMPOSE_PATH --host $SSH_SERVER down
  needs: ['deploy_staging']
  when: manual
  only:
    refs:
      - staging
